### ISSUE TITLE
More pictures please

### ISSUE THREAD

**Issue by E3V3A** [asimhsidd/MMM-TracCar#1]
This module look cool.

* Can you show some pictures how the map window look on the MM screen? 
* Does the window center follow on the tracked device?

**Comment by asimhsidd** [comment]
Thanks for your comment. There is a picture attached in the readme document. Yes the map's center follows the tracked device. For multiple tracked devices, it even zooms to right level making sure all devices are visible.

**Comment by E3V3A** [comment]
@asimhsidd 
>  There is a picture attached in the readme document.

I know, that's why I was asking to see how it relates to the other modules shown. 
* Does it cover the entire screen? 
* Does it have a border?
* Is it iFrame based?
* Can it be enabled/disabled?
* Can it be re-sized?
* Can there be more than one map?

**Comment by asimhsidd** [comment]
I have updated Readme document. Hope it answers your questions. Thanks for your interest.

**Comment by asimhsidd** [comment]
E3V3A, I have further made changes to the module. Now the look of the map container can be adjusted by the user through config settings.

**Comment by asimhsidd** [comment]
And I have not yet built my personal Magic Mirror, I am only building these modules on my pc while testing on chrome. So I dont have pictures!
Hopefully one day!
👍
