### ISSUE TITLE
Google API Key

### ISSUE THREAD

**Issue by hutny1980** [asimhsidd/MMM-TracCar#3]
Looks like Google are now charging for their Maps API. Any consideration to move to another, free mapping api service?

Thanks,
G

**Comment by asimhsidd** [comment]
@hutny1980 Tell me which service would you like me to port to, I will do it for you!

**Comment by hutny1980** [comment]
Wow - thank you @asimhsidd 

I'm not sure what other suitable alternatives are out there - OpenStreetMap?

**Comment by asimhsidd** [comment]
@hutny1980 I will see into it, by the way you may also use Traccar's own console in a iframe on your mirror! :)

**Comment by hutny1980** [comment]
Thank you @asimhsidd - will use the iFrame as a alternative.

I'm trying to work out whether by using the Google Maps API I will incur monthly charges - the Google Documentation is not very clear. Any ideas?

https://manifesto.co.uk/google-maps-api-pricing-changes/

**Comment by asimhsidd** [comment]
@hutny1980 
Google is offering $200 worth of of API calls for free per month, which means approximately 40,000 free Geolocation calls per month. If you divide 40,000 by 720 (hours in a month), this gives you 55 calls per hour. So I believe you are safe to use Google Maps, just put the frequency of update to 2+ minutes in the tracking app... let me know if you need me to further elaborate on this.

**Comment by hutny1980** [comment]
last question - in the app, frequency is 300 - is that seconds; milliseconds; minutes?

**Comment by asimhsidd** [comment]
@hutny1980 thats definitely in seconds... :)

**Comment by hutny1980** [comment]
@asimhsidd - thanks for all your help. I've tried to get this module working, but it simply says MMM-TracCar is Loading. The App and Website are working fine and strongly suspect it's something to do with the Google Geolocation API that I've tried to setup in the Google Console. 

Add all my payment details and enabled the GeoLocation API in the Google Console. Created a Credentials Key and added that to the config.js file.

Not sure what I'm doing wrong - any ideas!?

**Comment by asimhsidd** [comment]
please copy paste your console log here..

**Comment by hutny1980** [comment]
1|mm       | > magicmirror@2.4.1 start /home/pi/MagicMirror
1|mm       | > sh run-start.sh
1|mm       | Starting MagicMirror: v2.4.1
1|mm       | Loading config ...
1|mm       | Loading module helpers ...
1|mm       | No helper found for module: alert.
1|mm       | Initializing new module helper ...
1|mm       | Module helper loaded: updatenotification
1|mm       | No helper found for module: clock.
1|mm       | Initializing new module helper ...
1|mm       | Module helper loaded: MMM-TracCar
1|mm       | No helper found for module: MMM-iFrame.
1|mm       | Initializing new module helper ...
1|mm       | Module helper loaded: MMM-Strava
1|mm       | Initializing new module helper ...
1|mm       | Module helper loaded: MMM-WunderGround
1|mm       | Initializing new module helper ...
1|mm       | Module helper loaded: MMM-Todoist
1|mm       | Initializing new module helper ...
1|mm       | Module helper loaded: newsfeed
1|mm       | Initializing new module helper ...
1|mm       | Module helper loaded: MMM-Mail
1|mm       | All module helpers loaded.
1|mm       | Starting server on port 8080 ...
1|mm       | You're using a full whitelist configuration to allow                                                                        for all IPs
1|mm       | Server started ...
1|mm       | Connecting socket for: updatenotification
1|mm       | Connecting socket for: MMM-TracCar
1|mm       | Starting NodeHelper for MMM-TracCarmodule.
1|mm       | Connecting socket for: MMM-Strava
1|mm       | Starting module: MMM-Strava
1|mm       | Connecting socket for: MMM-WunderGround
1|mm       | MMM-WunderGround helper started ...
1|mm       | Connecting socket for: MMM-Todoist
1|mm       | Starting node helper for: MMM-Todoist
1|mm       | Connecting socket for: newsfeed
1|mm       | Starting module: newsfeed
1|mm       | Connecting socket for: MMM-Mail
1|mm       | MMM-Mail helper started ...
1|mm       | Sockets connected & modules started ...
1|mm       | Launching application.
1|mm       | libGL error: MESA-LOADER: failed to retrieve device i                                                                       nformation
1|mm       | MESA-LOADER: failed to retrieve device information
1|mm       | MESA-LOADER: failed to retrieve device information
1|mm       | MMM-Strava: Make request: /api/v3/athletes/7517611/st                                                                       ats (GET)
1|mm       | GET_WUNDERGROUND
1|mm       | Create new news fetcher for url: http://feeds.feedbur                                                                       ner.com/TechCrunch/ - Interval: 300000
1|mm       | Create new news fetcher for url: http://feeds.bbci.co                                                                       .uk/news/rss.xml?edition=int# - Interval: 300000
1|mm       | Create new news fetcher for url: http://feeds.bbci.co                                                                       .uk/news/england/york_and_north_yorkshire/rss.xml - Interval: 3000                                                                       00
1|mm       | Create new news fetcher for url: https://www.theguard                                                                       ian.com/uk/rss - Interval: 300000
1|mm       | Create new news fetcher for url: http://www.dailymail                                                                       .co.uk/tvshowbiz/index.rss - Interval: 300000
1|mm       | Create new news fetcher for url: http://www.dailymail                                                                       .co.uk/money/index.rss - Interval: 300000
1|mm       | Create new news fetcher for url: http://feeds.bbci.co                                                                       .uk/sport/football/rss.xml?edition=int - Interval: 300000
[1|mm       | connected
1|mm       | MMM-Mail-Helper: Mailbox Closed: INBOX
1|mm       | Mail-Seach complete

**Comment by asimhsidd** [comment]
there is nothing much there.. can you switch off all other modules and then send me the console log.. thanks!

**Comment by hutny1980** [comment]
Here's my config, with sensitive data xxxx out:-

{
                        module: 'MMM-TracCar',
                        position: 'bottom_left',
                        config: {
                                url: "http://demo5.traccar.org", // Traccar Server URL (free server @ http://demo5.traccar.org )
                                username: "gxxxxg.hxxxxt@gmail.com", // Traccar Account username (email) (btw, there is a free account option too!) :)
                                pass: "hxxxxxxxxe", // Traccar Account Password
                                gmapid: "AIzaSyxxxxxxxxxxxxxxxxxxxxxxxxxxxi41XZxH8", // Google Apps key
                                map_width: "300", // width of the map element
                                map_height: "400", // height of the map element
                                map_border_radius: "10", // border radius of the map element (optional)
                                map_shadow_color: "POWDERBLUE", // shadow color of the border element (optional)
                        }
        },

**Comment by asimhsidd** [comment]
the config looks okay!
Just to try that your google maps API is working... 

1. go to [Google Developers Code Sample](https://developers.google.com/maps/documentation/javascript/examples/map-simple)
2. go to [HTMLEDIT](http://htmledit.squarefree.com/) and paste the code there
3. change the API Key to yours

**Comment by hutny1980** [comment]
Ah - looks like progress is being made - by deleting all the other modules in the config.js file it loads successfully.

I'll go through and remove each one at a time and see if I can pinpoint the culprit.

**Comment by asimhsidd** [comment]
Great!! So there is a conflict among the modules! Now you know what to do, let me know if I can close this thread! Goodluck!

**Comment by hutny1980** [comment]
@asimhsidd - huge thanks for all your help - I managed to identify it was another module (iFrame) that was causing the module not to load. I've deleted the config for the iFrame Module and now it's working fine.

Thanks again for all your help and a fantastic module you've created - keep up the good work!!

G

**Comment by asimhsidd** [comment]
@hutny1980 thanks man! appreciate your comments! goodluck!

**Comment by smartthinks** [comment]
@asimhsidd Thanks for this APP.
>  I will see into it, by the way you may also use Traccar's own console in a iframe on your mirror! :)

Thanks for this great MMM but ken you tell me if you fixt it on opensteetmaps.org??
